export const sports = [
  { id: 'all-live', name: 'All Live', icon: 'live', to: '/live', count: 86 },
  { id: 'favorites', name: 'Favorites', icon: 'star', to: '/favorites' },
  { id: 'parlays', name: 'Top Parlays', icon: 'layers', to: '/parlays' },
  { id: 'promos', name: 'Promotions', icon: 'gift', to: '/promotions' },
  { id: 'cricket', name: 'Cricket', icon: 'cricket', to: '/sport/cricket', color: '#61D6B0' },
  { id: 'football', name: 'Football', icon: 'football', to: '/sport/football', color: '#43C7E8' },
  { id: 'basketball', name: 'Basketball', icon: 'basketball', to: '/sport/basketball', color: '#D5AA50' },
  { id: 'tennis', name: 'Tennis', icon: 'tennis', to: '/sport/tennis', color: '#61D6B0' },
  { id: 'table-tennis', name: 'Table Tennis', icon: 'table', to: '/sport/table-tennis', color: '#43C7E8' },
  { id: 'horse', name: 'Horse Racing', icon: 'horse', to: '/sport/horse-racing', color: '#A66ACB' },
]

export const leagues = [
  { group: 'FOOTBALL · POPULAR', items: [
    { name: 'UEFA Champions League', sub: 'League Phase', flag: '🏆' },
    { name: 'UEFA Europa League', sub: 'League Phase', flag: '🏆' },
    { name: 'UEFA Conference League', sub: 'League Phase', flag: '🏆' },
    { name: 'Premier League', sub: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
    { name: 'LaLiga', sub: 'Spain', flag: '🇪🇸' },
    { name: 'Serie A', sub: 'Italy', flag: '🇮🇹' },
    { name: 'Bundesliga', sub: 'Germany', flag: '🇩🇪' },
    { name: 'Ligue 1', sub: 'France', flag: '🇫🇷' },
    { name: 'MLS', sub: 'USA', flag: '🇺🇸' },
  ]},
  { group: 'BASKETBALL', items: [
    { name: 'NBA', sub: 'Regular season', flag: '🏀' },
    { name: 'EuroLeague', sub: 'Regular season', flag: '🇪🇺' },
    { name: 'WNBA', sub: 'Regular season', flag: '🏀' },
  ]},
  { group: 'OTHER', items: [
    { name: 'Setka Cup', sub: 'Table Tennis', flag: '🏓' },
    { name: 'Stake Ranked', sub: 'Counter-Strike', flag: '🎯' },
    { name: 'NHL', sub: 'Regular season', flag: '🏒' },
  ]},
]

export const shortcuts = [
  { name: 'Promo', to: '/promotions', color: '#A66ACB' },
  { name: 'Crypto', to: '/account/deposit', color: '#D5AA50' },
  { name: 'App', to: '/more', color: '#61D6B0' },
  { name: 'All Live', to: '/live', color: '#F16F78' },
  { name: 'Asian Games 2026', to: '/sport/cricket', color: '#43C7E8' },
  { name: 'EPL', to: '/sport/football', color: '#43C7E8' },
  { name: 'WNBA', to: '/sport/basketball', color: '#A66ACB' },
  { name: 'CSL', to: '/sport/football', color: '#61D6B0' },
  { name: 'Virtual Cricket', to: '/casino/virtual-sports', color: '#61D6B0' },
  { name: 'E-Football', to: '/casino/virtual-sports', color: '#A66ACB' },
  { name: 'Cricket Roulette', to: '/casino/tv-games', color: '#F16F78' },
  { name: 'Setka Cup', to: '/sport/table-tennis', color: '#43C7E8' },
  { name: 'Horse Racing', to: '/sport/horse-racing', color: '#A66ACB' },
  { name: 'BSKT Cup', to: '/sport/basketball', color: '#D5AA50' },
  { name: 'VIP Club', to: '/vip', color: '#D5AA50' },
]

export const matches = [
  {
    id: 'c1',
    sport: 'cricket',
    league: 'Cricket. Youth teams. ODI U-19. 2nd ODI',
    live: true,
    time: 'INNINGS 1',
    home: 'India U-19',
    away: 'Australia U-19',
    score: ['34/7', '222/6 (37.2)'],
    extras: ['341', '222'],
    markets: [{ id: 'c1-more', label: '2 available outcomes', odd: null }],
  },
  {
    id: 'f1',
    sport: 'football',
    league: 'Football. Argentina. Liga Profesional',
    live: false,
    time: 'TODAY, 23:10',
    extra: '+3323',
    home: 'CA Aldosivi',
    away: 'Atletico Tucuman',
    markets: [
      { id: 'f1-1', label: '1', odd: 3.16 },
      { id: 'f1-x', label: 'X', odd: 2.95 },
      { id: 'f1-2', label: '2', odd: 2.44 },
    ],
  },
  {
    id: 'f2',
    sport: 'football',
    league: 'Football. Argentina. Liga Profesional',
    live: false,
    time: 'TODAY, 23:30',
    extra: '+1669',
    home: 'Barracas Central',
    away: 'Independiente Rivadavia',
    markets: [
      { id: 'f2-1', label: '1', odd: 3.31 },
      { id: 'f2-x', label: 'X', odd: 2.94 },
      { id: 'f2-2', label: '2', odd: 2.36 },
    ],
  },
  {
    id: 'f3',
    sport: 'football',
    league: 'Football. Argentina. Liga Profesional',
    live: false,
    time: 'TOMORROW, 05:45',
    extra: '+2387',
    home: 'Lanus',
    away: 'Estudiantes La Plata',
    markets: [
      { id: 'f3-1', label: '1', odd: 2.17 },
      { id: 'f3-x', label: 'X', odd: 2.97 },
      { id: 'f3-2', label: '2', odd: 3.74 },
    ],
  },
  {
    id: 'f4',
    sport: 'football',
    league: 'Premier League',
    live: true,
    time: '64’',
    extra: '+412',
    home: 'Arsenal',
    away: 'Chelsea',
    score: ['2', '1'],
    markets: [
      { id: 'f4-1', label: '1', odd: 1.72 },
      { id: 'f4-x', label: 'X', odd: 3.85 },
      { id: 'f4-2', label: '2', odd: 4.60 },
    ],
  },
  {
    id: 'f5',
    sport: 'football',
    league: 'LaLiga',
    live: true,
    time: '12’',
    extra: '+298',
    home: 'Real Madrid',
    away: 'Sevilla',
    score: ['1', '0'],
    markets: [
      { id: 'f5-1', label: '1', odd: 1.28 },
      { id: 'f5-x', label: 'X', odd: 5.40 },
      { id: 'f5-2', label: '2', odd: 9.80 },
    ],
  },
  {
    id: 'b1',
    sport: 'basketball',
    league: 'NBA. Regular season',
    live: false,
    time: 'TODAY, 06:30',
    extra: '+180',
    home: 'Boston Celtics',
    away: 'Miami Heat',
    markets: [
      { id: 'b1-1', label: '1', odd: 1.55 },
      { id: 'b1-2', label: '2', odd: 2.48 },
    ],
  },
  {
    id: 't1',
    sport: 'tennis',
    league: 'ATP. Shanghai Masters',
    live: true,
    time: 'SET 2',
    extra: '+64',
    home: 'J. Sinner',
    away: 'C. Alcaraz',
    score: ['6 3', '4 4'],
    markets: [
      { id: 't1-1', label: '1', odd: 1.90 },
      { id: 't1-2', label: '2', odd: 1.92 },
    ],
  },
]

export const matchMarkets = [
  { name: '1X2', rows: [[{ label: '1', odd: 1.72 }, { label: 'X', odd: 3.85 }, { label: '2', odd: 4.60 }]] },
  { name: 'Double Chance', rows: [[{ label: '1X', odd: 1.22 }, { label: '12', odd: 1.28 }, { label: 'X2', odd: 2.10 }]] },
  { name: 'Total', rows: [[{ label: 'Over 2.5', odd: 1.85 }, { label: 'Under 2.5', odd: 1.98 }]] },
  { name: 'Both Teams To Score', rows: [[{ label: 'Yes', odd: 1.74 }, { label: 'No', odd: 2.08 }]] },
  { name: 'Asian Handicap', rows: [[{ label: 'Home -0.5', odd: 1.90 }, { label: 'Away +0.5', odd: 1.92 }]] },
  { name: 'Next Goal', rows: [[{ label: 'Home', odd: 2.10 }, { label: 'None', odd: 6.50 }, { label: 'Away', odd: 3.40 }]] },
]

export const games = [
  { id: 'aviator', name: 'Aviator', cat: 'instant', hue: 0 },
  { id: 'jetx', name: 'JetX', cat: 'instant', hue: 200 },
  { id: 'rummy', name: 'Rummy', cat: 'instant', hue: 30 },
  { id: 'aviatrix', name: 'Aviatrix', cat: 'instant', hue: 260 },
  { id: 'garuda', name: 'Fortune Garuda 500', cat: 'slots', hue: 45 },
  { id: 'orizon', name: 'Orizon', cat: 'slots', hue: 190 },
  { id: 'andar', name: 'Andar Bahar', cat: 'live', hue: 15 },
  { id: 'ultimate', name: 'Ultimate Hot', cat: 'slots', hue: 330 },
  { id: 'money', name: 'Money Time', cat: 'live', hue: 50 },
  { id: 'coins', name: '777 coins', cat: 'slots', hue: 40 },
  { id: 'pmslots', name: 'Bullwave Slots', cat: 'slots', hue: 168 },
  { id: 'instants', name: 'Bullwave Instants', cat: 'instant', hue: 194 },
  { id: 'coinflip', name: 'Coin Flip', cat: 'instant', hue: 210 },
  { id: 'mines', name: 'Crystal Mines', cat: 'instant', hue: 280 },
  { id: 'ice', name: 'Ice Fishing', cat: 'live', hue: 195 },
  { id: 'wonderland', name: 'Adventures Beyond Wonderland', cat: 'live', hue: 300 },
  { id: 'lightning', name: 'XXXtreme Lightning Roulette', cat: 'live', hue: 350 },
  { id: 'monopoly', name: 'MONOPOLY Big Baller', cat: 'live', hue: 25 },
  { id: 'reddoor', name: 'Red Door Roulette', cat: 'live', hue: 0 },
  { id: 'crash', name: 'Crash X', cat: 'instant', hue: 10 },
  { id: 'plinko', name: 'Plinko', cat: 'instant', hue: 170 },
  { id: 'keno', name: 'Keno', cat: 'tv', hue: 220 },
  { id: 'virtualc', name: 'Virtual Cricket', cat: 'virtual', hue: 130 },
  { id: 'efootball', name: 'E-Football', cat: 'virtual', hue: 145 },
]

export const promotions = [
  { id: 1, title: 'Welcome Bonus', text: 'Get Live Casino Bonus 100% up to ₹50,000', cta: 'Get Now', tone: 'purple' },
  { id: 2, title: 'First Deposit Bonus', text: '100% up to ₹25,000 on Sports', cta: 'Claim Bonus', tone: 'blue' },
  { id: 3, title: 'Crypto Boost', text: 'Extra 10% on USDT deposits', cta: 'Deposit', tone: 'gold' },
  { id: 4, title: 'Aviator Cashback', text: '5% weekly cashback on crash games', cta: 'Play Now', tone: 'red' },
  { id: 5, title: 'VIP Reload', text: 'Exclusive reload for Bullwave Club VIP', cta: 'Join VIP', tone: 'dark' },
  { id: 6, title: 'Acca Boost', text: 'Up to 50% extra on 5+ fold parlays', cta: 'Bet Now', tone: 'green' },
]

export const faqs = [
  { q: 'How do I create an account?', a: 'Tap Sign up, enter your phone number, set a password, and confirm the SMS code.' },
  { q: 'How do I make a deposit?', a: 'Open My Account → Deposit and choose UPI, net banking, wallet, or crypto.' },
  { q: 'How long do withdrawals take?', a: 'Most UPI withdrawals are processed within minutes after verification.' },
  { q: 'What odds formats are available?', a: 'Decimal, fractional, and American formats can be switched in the menu.' },
  { q: 'Is there a welcome bonus?', a: 'Yes. New players can claim a Live Casino welcome bonus of 100% up to ₹50,000.' },
]

export const languages = [
  { code: 'HI', name: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'EN', name: 'English', flag: '🇬🇧', dir: 'ltr' },
  { code: 'BN', name: 'বাংলা', flag: '🇮🇳', dir: 'ltr' },
  { code: 'TE', name: 'తెలుగు', flag: '🇮🇳', dir: 'ltr' },
  { code: 'MR', name: 'मराठी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'TA', name: 'தமிழ்', flag: '🇮🇳', dir: 'ltr' },
  { code: 'KN', name: 'ಕನ್ನಡ', flag: '🇮🇳', dir: 'ltr' },
  { code: 'ML', name: 'മലയാളം', flag: '🇮🇳', dir: 'ltr' },
  { code: 'GU', name: 'ગુજરાતી', flag: '🇮🇳', dir: 'ltr' },
  { code: 'PA', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳', dir: 'ltr' },
  { code: 'AR', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'UR', name: 'اردو', flag: '🇵🇰', dir: 'rtl' },
  { code: 'FA', name: 'فارسی', flag: '🇮🇷', dir: 'rtl' },
  { code: 'HE', name: 'עברית', flag: '🇮🇱', dir: 'rtl' },
  { code: 'FR', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'ES', name: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'PT', name: 'Português', flag: '🇧🇷', dir: 'ltr' },
  { code: 'DE', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'IT', name: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'RU', name: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'TR', name: 'Türkçe', flag: '🇹🇷', dir: 'ltr' },
  { code: 'ZH', name: '中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'JA', name: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'KO', name: '한국어', flag: '🇰🇷', dir: 'ltr' },
  { code: 'ID', name: 'Bahasa Indonesia', flag: '🇮🇩', dir: 'ltr' },
  { code: 'TH', name: 'ไทย', flag: '🇹🇭', dir: 'ltr' },
  { code: 'VI', name: 'Tiếng Việt', flag: '🇻🇳', dir: 'ltr' },
]

export const accountLinks = [
  { name: 'Deposit', to: '/account/deposit', icon: 'plus' },
  { name: 'Withdraw', to: '/account/withdraw', icon: 'minus' },
  { name: 'My bets', to: '/account/bets', icon: 'ticket' },
  { name: 'Bonuses', to: '/promotions', icon: 'gift' },
  { name: 'Verification', to: '/account/verify', icon: 'shield' },
  { name: 'Settings', to: '/account/settings', icon: 'gear' },
  { name: 'Responsible gaming', to: '/faq', icon: 'heart' },
]
