export const sports = [
  { id: 'all-live', name: 'All Live', icon: 'live', image: '🔥', to: '/live', count: 86 },
  { id: 'favorites', name: 'Favorites', icon: 'star', image: '⭐', to: '/favorites' },
  { id: 'parlays', name: 'Top Parlays', icon: 'layers', image: '🟩', to: '/parlays' },
  { id: 'promos', name: 'Promotions', icon: 'gift', image: '🎁', to: '/promotions' },
  { id: 'cricket', name: 'Cricket', icon: 'cricket', image: '🏏', to: '/sport/cricket', color: '#61D6B0' },
  { id: 'football', name: 'Football', icon: 'football', image: '⚽', to: '/sport/football', color: '#43C7E8' },
  { id: 'basketball', name: 'Basketball', icon: 'basketball', image: '🏀', to: '/sport/basketball', color: '#D5AA50' },
  { id: 'tennis', name: 'Tennis', icon: 'tennis', image: '🎾', to: '/sport/tennis', color: '#61D6B0' },
  { id: 'table-tennis', name: 'Table Tennis', icon: 'table', image: '🏓', to: '/sport/table-tennis', color: '#43C7E8' },
  { id: 'horse', name: 'Horse Racing', icon: 'horse', image: '🏇', to: '/sport/horse-racing', color: '#A66ACB' },
]

export const leagues = [
  { group: 'FOOTBALL · POPULAR', to: '/sport/football', items: [
    { name: 'League Phase', sub: 'UEFA Champions League', code: 'ucl' },
    { name: 'League Phase', sub: 'UEFA Europa League', code: 'uel' },
    { name: 'League Phase', sub: 'UEFA Conference League', code: 'uecl' },
    { name: 'Premier League', sub: 'England', code: 'england' },
    { name: 'LaLiga', sub: 'Spain', code: 'spain' },
    { name: 'Serie A', sub: 'Italy', code: 'italy' },
    { name: 'Bundesliga', sub: 'Germany', code: 'germany' },
    { name: 'Ligue 1', sub: 'France', code: 'france' },
    { name: 'MLS', sub: 'USA', code: 'usa' },
  ]},
  { group: 'BASKETBALL', to: '/sport/basketball', items: [
    { name: 'NBA', sub: 'USA · Regular season', code: 'basketball' },
    { name: 'EuroLeague', sub: 'Europe · Regular season', code: 'europe' },
    { name: 'WNBA', sub: 'USA · Regular season', code: 'basketball' },
  ]},
  { group: 'OTHER', to: '/live', items: [
    { name: 'Setka Cup', sub: 'Table Tennis', code: 'table-tennis' },
    { name: 'Stake Ranked', sub: 'Counter-Strike', code: 'esports' },
    { name: 'NHL', sub: 'Ice Hockey', code: 'hockey' },
  ]},
]

export const shortcuts = [
  { name: 'Promo', image: 'promo', to: '/promotions', color: '#A66ACB' },
  { name: 'Crypto', image: 'crypto', to: '/account/deposit', color: '#D5AA50' },
  { name: 'App', image: 'app', to: '/more', color: '#61D6B0' },
  { name: 'All Live', image: 'live', to: '/live', color: '#F16F78' },
  { name: 'Asian Games 2026', image: 'asian', to: '/sport/cricket', color: '#43C7E8' },
  { name: 'EPL', image: 'football', to: '/sport/football', color: '#43C7E8' },
  { name: 'WNBA', image: 'basketball', to: '/sport/basketball', color: '#A66ACB' },
  { name: 'CSL', image: 'csl', to: '/sport/football', color: '#61D6B0' },
  { name: 'Virtual Cricket', image: 'cricket', to: '/casino/virtual-sports', color: '#61D6B0' },
  { name: 'E-Football', image: 'esports', to: '/casino/virtual-sports', color: '#A66ACB' },
  { name: 'Cricket Roulette', image: 'roulette', to: '/casino/tv-games', color: '#F16F78' },
  { name: 'Setka Cup', image: 'table', to: '/sport/table-tennis', color: '#43C7E8' },
  { name: 'Horse Racing', image: 'horse', to: '/sport/horse-racing', color: '#A66ACB' },
  { name: 'BSKT Cup', image: 'cup', to: '/sport/basketball', color: '#D5AA50' },
  { name: 'VIP Club', image: 'vip', to: '/vip', color: '#D5AA50' },
]

export const matches = [
  {
    id: 'c1',
    sport: 'cricket',
    league: 'Cricket. Youth teams. ODI U-19. 2nd ODI',
    live: true,
    time: 'INNINGS 1',
    home: 'India U-19',
    away: 'Australia U-19',
    score: ['34/7', '222/6 (37.2)'],
    extras: ['341', '222'],
    markets: [{ id: 'c1-more', label: '2 available outcomes', odd: null }],
  },
  {
    id: 'f1',
    sport: 'football',
    league: 'Football. Argentina. Liga Profesional',
    live: false,
    time: 'TODAY, 23:10',
    extra: '+3323',
    home: 'CA Aldosivi',
    away: 'Atletico Tucuman',
    markets: [
      { id: 'f1-1', label: '1', odd: 3.16 },
      { id: 'f1-x', label: 'X', odd: 2.95 },
      { id: 'f1-2', label: '2', odd: 2.44 },
    ],
  },
  {
    id: 'f2',
    sport: 'football',
    league: 'Football. Argentina. Liga Profesional',
    live: false,
    time: 'TODAY, 23:30',
    extra: '+1669',
    home: 'Barracas Central',
    away: 'Independiente Rivadavia',
    markets: [
      { id: 'f2-1', label: '1', odd: 3.31 },
      { id: 'f2-x', label: 'X', odd: 2.94 },
      { id: 'f2-2', label: '2', odd: 2.36 },
    ],
  },
  {
    id: 'f3',
    sport: 'football',
    league: 'Football. Argentina. Liga Profesional',
    live: false,
    time: 'TOMORROW, 05:45',
    extra: '+2387',
    home: 'Lanus',
    away: 'Estudiantes La Plata',
    markets: [
      { id: 'f3-1', label: '1', odd: 2.17 },
      { id: 'f3-x', label: 'X', odd: 2.97 },
      { id: 'f3-2', label: '2', odd: 3.74 },
    ],
  },
  {
    id: 'f4',
    sport: 'football',
    league: 'Premier League',
    live: true,
    time: '64’',
    extra: '+412',
    home: 'Arsenal',
    away: 'Chelsea',
    score: ['2', '1'],
    markets: [
      { id: 'f4-1', label: '1', odd: 1.72 },
      { id: 'f4-x', label: 'X', odd: 3.85 },
      { id: 'f4-2', label: '2', odd: 4.60 },
    ],
  },
  {
    id: 'f5',
    sport: 'football',
    league: 'LaLiga',
    live: true,
    time: '12’',
    extra: '+298',
    home: 'Real Madrid',
    away: 'Sevilla',
    score: ['1', '0'],
    markets: [
      { id: 'f5-1', label: '1', odd: 1.28 },
      { id: 'f5-x', label: 'X', odd: 5.40 },
      { id: 'f5-2', label: '2', odd: 9.80 },
    ],
  },
  {
    id: 'b1',
    sport: 'basketball',
    league: 'NBA. Regular season',
    live: false,
    time: 'TODAY, 06:30',
    extra: '+180',
    home: 'Boston Celtics',
    away: 'Miami Heat',
    markets: [
      { id: 'b1-1', label: '1', odd: 1.55 },
      { id: 'b1-2', label: '2', odd: 2.48 },
    ],
  },
  {
    id: 't1',
    sport: 'tennis',
    league: 'ATP. Shanghai Masters',
    live: true,
    time: 'SET 2',
    extra: '+64',
    home: 'J. Sinner',
    away: 'C. Alcaraz',
    score: ['6 3', '4 4'],
    markets: [
      { id: 't1-1', label: '1', odd: 1.90 },
      { id: 't1-2', label: '2', odd: 1.92 },
    ],
  },
]

export const matchMarkets = [
  { name: '1X2', rows: [[{ label: '1', odd: 1.72 }, { label: 'X', odd: 3.85 }, { label: '2', odd: 4.60 }]] },
  { name: 'Double Chance', rows: [[{ label: '1X', odd: 1.22 }, { label: '12', odd: 1.28 }, { label: 'X2', odd: 2.10 }]] },
  { name: 'Total', rows: [[{ label: 'Over 2.5', odd: 1.85 }, { label: 'Under 2.5', odd: 1.98 }]] },
  { name: 'Both Teams To Score', rows: [[{ label: 'Yes', odd: 1.74 }, { label: 'No', odd: 2.08 }]] },
  { name: 'Asian Handicap', rows: [[{ label: 'Home -0.5', odd: 1.90 }, { label: 'Away +0.5', odd: 1.92 }]] },
  { name: 'Next Goal', rows: [[{ label: 'Home', odd: 2.10 }, { label: 'None', odd: 6.50 }, { label: 'Away', odd: 3.40 }]] },
]

export const games = [
  { id: 'aviator', name: 'Aviator', cat: 'instant', hue: 0 },
  { id: 'jetx', name: 'JetX', cat: 'instant', hue: 200 },
  { id: 'rummy', name: 'Rummy', cat: 'instant', hue: 30 },
  { id: 'aviatrix', name: 'Aviatrix', cat: 'instant', hue: 260 },
  { id: 'garuda', name: 'Fortune Garuda 500', cat: 'slots', hue: 45 },
  { id: 'orizon', name: 'Orizon', cat: 'slots', hue: 190 },
  { id: 'andar', name: 'Andar Bahar', cat: 'live', hue: 15 },
  { id: 'ultimate', name: 'Ultimate Hot', cat: 'slots', hue: 330 },
  { id: 'money', name: 'Money Time', cat: 'live', hue: 50 },
  { id: 'coins', name: '777 coins', cat: 'slots', hue: 40 },
  { id: 'pmslots', name: 'Bullwave Slots', cat: 'slots', hue: 168 },
  { id: 'instants', name: 'Bullwave Instants', cat: 'instant', hue: 194 },
  { id: 'coinflip', name: 'Coin Flip', cat: 'instant', hue: 210 },
  { id: 'mines', name: 'Crystal Mines', cat: 'instant', hue: 280 },
  { id: 'ice', name: 'Ice Fishing', cat: 'live', hue: 195 },
  { id: 'wonderland', name: 'Adventures Beyond Wonderland', cat: 'live', hue: 300 },
  { id: 'lightning', name: 'XXXtreme Lightning Roulette', cat: 'live', hue: 350 },
  { id: 'monopoly', name: 'MONOPOLY Big Baller', cat: 'live', hue: 25 },
  { id: 'reddoor', name: 'Red Door Roulette', cat: 'live', hue: 0 },
  { id: 'crash', name: 'Crash X', cat: 'instant', hue: 10 },
  { id: 'plinko', name: 'Plinko', cat: 'instant', hue: 170 },
  { id: 'keno', name: 'Keno', cat: 'tv', hue: 220 },
  { id: 'virtualc', name: 'Virtual Cricket', cat: 'virtual', hue: 130 },
  { id: 'efootball', name: 'E-Football', cat: 'virtual', hue: 145 },
]

export const promotions = [
  { id: 1, title: 'Spin the Bullwave Wheel', text: 'Unlock a surprise reward every day', cta: 'Open wheel', tone: 'purple', category: 'Casino', expires: '11m left', art: 'wheel' },
  { id: 2, title: '100% First Sports Bet Cover', text: 'Your first bet gets a safety net', cta: 'Activate', tone: 'blue', category: 'Sports', expires: '1h 12m left', art: 'shield' },
  { id: 3, title: 'Scratch Card: Hidden Bonus', text: 'Reveal free bets and instant prizes', cta: 'Scratch now', tone: 'gold', category: 'Instant', expires: '3d 1h left', art: 'scratch' },
  { id: 4, title: '₹3 Lakh Cricket Prize Pool', text: 'Make your picks and climb the table', cta: 'Join now', tone: 'green', category: 'Sports', expires: '6d 1h left', art: 'trophy' },
  { id: 5, title: 'Live Casino Reload + 40 Spins', text: 'Top up and receive a double reward', cta: 'Get bonus', tone: 'red', category: 'Casino', expires: '6d 1h left', art: 'chips' },
  { id: 6, title: '50 Free Bets: Chicken Dash', text: 'A playful new instant challenge', cta: 'Play now', tone: 'purple', category: 'Instant', expires: '6d 1h left', art: 'gift' },
  { id: 7, title: '777 Weekend Free Spins', text: 'Three days of boosted slot rewards', cta: 'Claim spins', tone: 'gold', category: 'Casino', expires: '2d 8h left', art: 'coin' },
  { id: 8, title: '150% Sports Welcome Bonus', text: 'A stronger start for new members', cta: 'Sign up', tone: 'blue', category: 'Sports', expires: 'New players', art: 'cricket' },
  { id: 9, title: 'Monday Royal Free Spins', text: 'Start the week with premium rewards', cta: 'Bet now', tone: 'dark', category: 'Casino', expires: 'Every Monday', art: 'crown' },
  { id: 10, title: '5% Crash Cashback', text: 'Weekly cashback on selected games', cta: 'Fly now', tone: 'red', category: 'Instant', expires: 'Weekly', art: 'rocket' },
]

export const faqs = [
  { q: 'How do I create an account?', a: 'Tap Sign up, enter your phone number, set a password, and confirm the SMS code.' },
  { q: 'How do I make a deposit?', a: 'Open My Account → Deposit and choose UPI, net banking, wallet, or crypto.' },
  { q: 'How long do withdrawals take?', a: 'Most UPI withdrawals are processed within minutes after verification.' },
  { q: 'What odds formats are available?', a: 'Decimal, fractional, and American formats can be switched in the menu.' },
  { q: 'Is there a welcome bonus?', a: 'Yes. New players can claim a Live Casino welcome bonus of 100% up to ₹50,000.' },
]

export const languages = [
  { code: 'HI', name: 'हिन्दी', country: 'IN', dir: 'ltr' },
  { code: 'EN', name: 'English', country: 'GB', dir: 'ltr' },
  { code: 'BN', name: 'বাংলা', country: 'IN', dir: 'ltr' },
  { code: 'TE', name: 'తెలుగు', country: 'IN', dir: 'ltr' },
  { code: 'MR', name: 'मराठी', country: 'IN', dir: 'ltr' },
  { code: 'TA', name: 'தமிழ்', country: 'IN', dir: 'ltr' },
  { code: 'KN', name: 'ಕನ್ನಡ', country: 'IN', dir: 'ltr' },
  { code: 'ML', name: 'മലയാളം', country: 'IN', dir: 'ltr' },
  { code: 'GU', name: 'ગુજરાતી', country: 'IN', dir: 'ltr' },
  { code: 'PA', name: 'ਪੰਜਾਬੀ', country: 'IN', dir: 'ltr' },
  { code: 'AR', name: 'العربية', country: 'SA', dir: 'rtl' },
  { code: 'UR', name: 'اردو', country: 'PK', dir: 'rtl' },
  { code: 'FA', name: 'فارسی', country: 'IR', dir: 'rtl' },
  { code: 'HE', name: 'עברית', country: 'IL', dir: 'rtl' },
  { code: 'FR', name: 'Français', country: 'FR', dir: 'ltr' },
  { code: 'ES', name: 'Español', country: 'ES', dir: 'ltr' },
  { code: 'PT', name: 'Português', country: 'BR', dir: 'ltr' },
  { code: 'DE', name: 'Deutsch', country: 'DE', dir: 'ltr' },
  { code: 'IT', name: 'Italiano', country: 'IT', dir: 'ltr' },
  { code: 'RU', name: 'Русский', country: 'RU', dir: 'ltr' },
  { code: 'TR', name: 'Türkçe', country: 'TR', dir: 'ltr' },
  { code: 'ZH', name: '中文', country: 'CN', dir: 'ltr' },
  { code: 'JA', name: '日本語', country: 'JP', dir: 'ltr' },
  { code: 'KO', name: '한국어', country: 'KR', dir: 'ltr' },
  { code: 'ID', name: 'Bahasa Indonesia', country: 'ID', dir: 'ltr' },
  { code: 'TH', name: 'ไทย', country: 'TH', dir: 'ltr' },
  { code: 'VI', name: 'Tiếng Việt', country: 'VN', dir: 'ltr' },
]

export const accountLinks = [
  { name: 'Deposit', to: '/account/deposit', icon: 'plus' },
  { name: 'Withdraw', to: '/account/withdraw', icon: 'minus' },
  { name: 'My bets', to: '/account/bets', icon: 'ticket' },
  { name: 'Bonuses', to: '/promotions', icon: 'gift' },
  { name: 'Verification', to: '/account/verify', icon: 'shield' },
  { name: 'Settings', to: '/account/settings', icon: 'gear' },
  { name: 'Responsible gaming', to: '/faq', icon: 'heart' },
]
